# Generated by Django 2.0.3 on 2018-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('logo', models.ImageField(blank=True, max_length=254, null=True, upload_to='logos')),
                ('api_key', models.CharField(max_length=40, unique=True, verbose_name='API key')),
            ],
        ),
    ]
