# Generated by Django 2.0.3 on 2018-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allow_mpesa_prepayment',
            field=models.BooleanField(default=False, verbose_name='allow MPesa prepayment'),
        ),
    ]
