# Generated by Django 2.0.3 on 2018-10-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20181008_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='allow_prepayment',
            field=models.BooleanField(default=False, verbose_name='Allow prepayment with MPesa from Payment Link form'),
        ),
    ]
