# Generated by Django 2.0.3 on 2018-10-12 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20181012_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Default delivery fee'),
        ),
    ]
