# Generated by Django 2.0.3 on 2018-08-01 13:23

import apps.core.mixins
from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('mpesa_gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link_id', models.CharField(blank=True, max_length=30, verbose_name='payment link id')),
                ('verification_code', models.CharField(blank=True, max_length=8, verbose_name='verification code')),
                ('order_number', models.CharField(max_length=255, verbose_name='order number')),
                ('status', models.PositiveSmallIntegerField(choices=[(9, 'Payment link'), (0, 'New'), (8, 'Processed'), (1, 'Submitted'), (2, 'Accepted'), (3, 'Assigned'), (4, 'Picked Up'), (5, 'Delivered'), (6, 'Completed'), (7, 'Canceled'), (10, 'Payment link canceled')], default=0, verbose_name='status')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='delivery fee')),
                ('buyer_name', models.CharField(max_length=128, verbose_name='buyer name')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='buyer phone')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='buyer email')),
                ('is_paid', models.BooleanField(default=False, verbose_name='order is paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('payment_method', models.PositiveIntegerField(blank=True, choices=[(0, 'Cash'), (1, 'MPesa')], null=True, verbose_name='payment method')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='driver')),
                ('shipping_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_from_shipping', to='shared.Location', verbose_name='shipping address')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.Shop', verbose_name='shop')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouses.Warehouse', verbose_name='warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(models.Model, apps.core.mixins.ModelDiffMixin),
        ),
        migrations.CreateModel(
            name='OrderAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Assigned'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='status')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.Order', verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed date')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Wrong PIN'), (3, 'Canceled'), (4, 'Wrong number'), (6, 'Wrong data'), (5, 'Expired'), (7, 'Failed')], default=0, verbose_name='Status')),
                ('transaction_uid', models.CharField(blank=True, max_length=50, verbose_name='Transaction UID')),
                ('payment_ref_id', models.CharField(blank=True, max_length=50, verbose_name='Payment Ref ID')),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', verbose_name='Errors')),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', verbose_name='Request data')),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', verbose_name='Response data')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.Order', verbose_name='Order')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='mpesa_gateway.MPesaTransaction', verbose_name='transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, verbose_name='product id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='KES', max_length=5, verbose_name='currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.Order', verbose_name='order')),
            ],
        ),
    ]
