# Generated by Django 2.0.3 on 2018-10-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_ref_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='request_data',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_uid',
        ),
    ]
