# Generated by Django 2.0.3 on 2018-10-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pending_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_link',
            field=models.BooleanField(default=False, verbose_name='order is payment link'),
        ),
    ]
