# Generated by Django 2.0.3 on 2018-10-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (8, 'Processed'), (1, 'Submitted'), (2, 'Accepted'), (3, 'Assigned'), (4, 'Picked Up'), (5, 'Delivered'), (6, 'Completed'), (7, 'Canceled')], default=0, verbose_name='status'),
        ),
    ]
