# Generated by Django 2.0.3 on 2018-10-10 19:36

from django.db import migrations


def update_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        if order.status == 9:
            order.status = 0
            order.is_payment_link = True

        if order.status == 10:
            order.status = 7

        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181010_0856'),
    ]

    operations = [
        migrations.RunPython(
            update_order_statuses,
            migrations.RunPython.noop,
        ),
    ]



