# Generated by Django 2.0.3 on 2018-10-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='product_id',
            new_name='item_id',
        ),
    ]
