# Generated by Django 2.0.3 on 2018-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181016_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='item_id',
            field=models.CharField(max_length=255, verbose_name='item id'),
        ),
    ]
