# Generated by Django 2.0.3 on 2018-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofintauser',
            name='changed_password',
            field=models.BooleanField(default=False, verbose_name='User has changed the default password'),
        ),
    ]
