# Generated by Django 2.0.3 on 2018-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPesaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('transaction_type', models.IntegerField(choices=[(1, 'TransactionReversal'), (2, 'CustomerPayBillOnline')], verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('party_a', models.CharField(max_length=100, verbose_name='party A')),
                ('party_b', models.CharField(max_length=100, verbose_name='party B')),
                ('phone_number', models.CharField(max_length=35, verbose_name='phone number')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Wrong PIN'), (3, 'Canceled'), (4, 'Wrong number'), (6, 'Wrong data'), (5, 'Expired'), (7, 'Failed')], default=0, verbose_name='status')),
                ('response_code', models.CharField(blank=True, choices=[('0', 'Success'), ('1', 'Insufficient Funds'), ('2', 'Less Than Minimum Transaction Value'), ('3', 'More Than Maximum Transaction Value'), ('4', 'Would Exceed Daily Transfer Limit'), ('5', 'Would Exceed Minimum Balance'), ('6', 'Unresolved Primary Party'), ('7', 'Unresolved Receiver Party'), ('8', 'Would Exceed Maximum Balance'), ('11', 'Debit Account Invalid'), ('12', 'Credit Account Invalid'), ('13', 'Unresolved Debit Account'), ('14', 'Unresolved Credit Account'), ('15', 'Duplicate Detected'), ('17', 'Internal Failure'), ('20', 'Unresolved Initiator'), ('26', 'Traffic blocking condition in place'), ('999', 'Unknown code')], max_length=5, verbose_name='response code')),
                ('response_description', models.TextField(blank=True, verbose_name='response description')),
                ('merchant_request_id', models.CharField(blank=True, max_length=255, verbose_name='merchant request id')),
                ('checkout_request_id', models.CharField(blank=True, max_length=255, verbose_name='checkout request id')),
                ('result_code', models.IntegerField(blank=True, null=True, verbose_name='result code')),
                ('result_desc', models.TextField(blank=True, verbose_name='result description')),
                ('customer_message', models.TextField(blank=True, verbose_name='customer message')),
                ('response_data', models.TextField(blank=True, verbose_name='response data')),
                ('callback_data', models.TextField(blank=True, verbose_name='callback data')),
            ],
        ),
    ]
