# Generated by Django 2.0.3 on 2018-08-01 13:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(verbose_name='item id')),
                ('name', models.CharField(max_length=255, verbose_name='item name')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='price')),
                ('currency', models.CharField(default='KES', max_length=5, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='shops.Shop', verbose_name='shop')),
            ],
        ),
    ]
