# Generated by Django 2.0.3 on 2018-10-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='price_list'),
        ),
    ]
