"""
Django settings for ofinta project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@=@7qn#b3zd@!)3&w(2i10z3*=fk^qieffjo3xtyn()2^iaml6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '88.80.189.208']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.sites',

    'apps.api',
    'apps.core',
    'apps.shared',
    'apps.administration.dashboard',
    'apps.administration.shop_accounts',

    'apps.management.dashboard',
    'apps.management.managers',
    'apps.management.orders',
    'apps.management.shops',
    'apps.management.drivers',
    'apps.management.warehouses',
    'apps.management.reports',
    'apps.management.chat',
    'apps.management.pricelist',

    'apps.demoshop',
    'apps.mpesa_gateway',

    'push_notifications',
    'datetimewidget',
    'bootstrap4',
    'rest_framework',
    'rest_framework_gis',
    'rest_framework.authtoken',
    'phonenumber_field',
    'mapwidgets',
    'impersonate',
    'channels',
    'svg',
    'django_select2',
    'django_file_form',
    'django_file_form.ajaxuploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'impersonate.middleware.ImpersonateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.RequestMiddleware'
]


ROOT_URLCONF = 'ofinta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard'
WSGI_APPLICATION = 'ofinta.wsgi.application'

IMPERSONATE = {
    'REDIRECT_URL': '/dashboard/',
    'PAGINATE_COUNT': 10,
}

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://tcv:T2ngrfpk@localhost:5432/ofintadb',
        conn_max_age=600
    )
}
DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
DATABASES['default']['TEST'] = {
    'NAME': 'ofinta_test'
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder'
)

AUTH_USER_MODEL = 'core.OfintaUser'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s TIMESTAMP=%(asctime)s MODULE=%(module)s '
                      'MESSAGE=%(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': sys.stdout,
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': [],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# EMAIL
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
PASSWORD_RESTORE_EMAIL = 'no_reply@ofinta.com'
NOTIFICATIONS_EMAIL = 'no_reply@ofinta.com'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.fastmail.com'
EMAIL_HOST_USER = 'no_reply@ofinta.com'
EMAIL_HOST_PASSWORD = '6tlrqq6mcx64l3jj'
EMAIL_PORT = 587

# Management dashboard
MAX_ORDERS_ON_DASH = 5
MAX_DRIVERS_ON_DASH = 5
MAX_WAREHOUSES_ON_DASH = 5
MAX_MANAGERS_ON_DASH = 5

# Google maps
GOOGLE_MAP_API_KEY = 'AIzaSyCIQZf58rsaXMU3bcAGr3UWF0RWz4_M7WU'

# django bootstrap 4
BOOTSTRAP4 = {

    # The URL to the jQuery JavaScript file
    'jquery_url': '//code.jquery.com/jquery.min.js',

    # The Bootstrap base URL
    'base_url': '//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/',

    # The complete URL to the Bootstrap CSS file (None means derive it from base_url)
    'css_url': None,

    # The complete URL to the Bootstrap CSS file (None means no theme)
    'theme_url': None,

    # The complete URL to the Bootstrap JavaScript file (None means derive it from base_url)
    'javascript_url': None,

    # Put JavaScript in the HEAD section of the HTML document (only relevant if you use bootstrap4.html)
    'javascript_in_head': False,

    # Include jQuery with Bootstrap JavaScript (affects django-bootstrap4 template tags)
    'include_jquery': False,

    # Label class to use in horizontal forms
    'horizontal_label_class': 'col-md-3',

    # Field class to use in horizontal forms
    'horizontal_field_class': 'col-md-9',

    # Set placeholder attributes to label if no placeholder is provided
    'set_placeholder': True,

    # Class to indicate required (better to set this in your Django form)
    'required_css_class': '',

    # Class to indicate error (better to set this in your Django form)
    'error_css_class': 'has-error',

    # Class to indicate success, meaning the field has valid input (better to set this in your Django form)
    'success_css_class': 'has-success',

    # Renderers (only set these if you have studied the source and understand the inner workings)
    'formset_renderers':{
        'default': 'bootstrap4.renderers.FormsetRenderer',
    },
    'form_renderers': {
        'default': 'bootstrap4.renderers.FormRenderer',
    },
    'field_renderers': {
        'default': 'bootstrap4.renderers.FieldRenderer',
        'inline': 'bootstrap4.renderers.InlineFieldRenderer',
    },
}

SITE_ID = 1

#######################################################
# DJANGO REST FRAMEWORK
#######################################################
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'ofinta.authentication.ShopTokenAuthentication',
        'ofinta.authentication.TokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}

# =========================================
# CHANNELS
# =========================================
ASGI_APPLICATION = 'ofinta.routing.application'
redis_host = os.environ.get('REDIS_HOST', 'localhost')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
        },
    },
}

# =========================================
# DRIVERS
# =========================================
DRIVER_UPDATE_TIMEOUT = 300  # seconds

# =========================================
# MPESA
# =========================================
SHOP_ID = 1
SHOP_KEY = '0a3d7a695183b575a51afff999202600d818aac78af25e712649708a4a596a54'
API_PAYMENT_URL = 'https://api-staging.begateway.com/beyag/transactions/payment'
API_REFUND_URL = 'https://api-staging.begateway.com//beyag/transactions/refund'
DEFAULT_HTTP_PROTOCOL = 'http'
MPESA_REQUEST_TIMEOUT = 60

MPESA_OAUTH2TOKEN_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate'
MPESA_STK_PUSH_URL = 'https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest'
MPESA_STK_REVERSAL_URL = 'https://sandbox.safaricom.co.ke/mpesa/reversal/v1/request'
MPESA_STK_PUSH_QUERY_URL = 'https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query'

MPESA_CONSUMER_KEY = 'dsAlwYN4g0M8teYStGHvhycZoFceilmM'
MPESA_CONSUMER_SECRET = 'EGGVW1f4hyqPdlCU'
MPESA_ACCOUNT_REFERENCE = 'fP6K2KuL'
MPESA_BUSINESS_SHORT_CODE = '174379'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'

# needed only for refund
MPESA_SECURITY_CREDENTIAL = 'MkKZF/u6ZHIwoOWbEQh6zCGBgcgkZ1kw24libp4xCUn3XU2JDLq+2SFZlD1DLSRXQf8dJHtDwDp8yCF4ZHDJS4QCxuvMpzWdDmpAcBPjqOSQXdjsAz7jNx2r/+iTXgSLPujgmIe3ubYVgSKb7BwA6DMedGb4JFDNfHD/prVss6zv01Zy0iMQ4fZ2OOyH3IqNDrEw3jKJ/xvcsn4nKud22Mj10DxaAiWH2sOkY9XA0916ZT/woXIBmX/YbpJhSUKkDPxmSa3UUyrY+Hbv21kmj7lPH6KwaA8rVKPPzRH/Wsn4itVvi2PvO3MAprdhSkJBy3VFwmdZQDJ4OQ2xNB7wQg=='

MPESA_RESULT_URL = 'http://88.80.189.208/mpesa-result/'
MPESA_TIMEOUT_URL = 'http://88.80.189.208/mpesa-timeout/'

# MPESA TEST MODE
MPESA_TEST_MODE = True

# response means immediate response after payment
MPESA_TEST_RESPONSES = {
    "0": 'Success',
    "1": 'Insufficient Funds',
    "2": 'Less Than Minimum Transaction Value',
    "3": 'More Than Maximum Transaction Value',
    "4": 'Would Exceed Daily Transfer Limit',
    "5": 'Would Exceed Minimum Balance',
    "6": 'Unresolved Primary Party',
    "7": 'Unresolved Receiver Party',
    "8": 'Would Exceed Maxiumum Balance',
    "11": 'Debit Account Invalid',
    "12": 'Credit Account Invalid',
    "13": 'Unresolved Debit Account',
    "14": 'Unresolved Credit Account',
    "15": 'Duplicate Detected',
    "17": 'Internal Failure',
    "20": 'Unresolved Initiator',
    "26": 'Traffic blocking condition in place',
}
MPESA_TEST_RESPONSE_CODE = "0"
MPESA_TEST_RESPONSE_STATUS_CODE = 200  # or 400
MPESA_TEST_RESPONSE_200_JSON = {
    "MerchantRequestID": "mr_id",
    "CheckoutRequestID": "cr_id",
    "ResponseCode": MPESA_TEST_RESPONSE_CODE,
    "ResponseDescription": "Success. Request accepted for processing",
    "CustomerMessage": "Success. Request accepted for processing"
}

# for 400 response code
MPESA_TEST_RESPONSE_TEXT = 'Bad Request - Invalid PhoneNumer'
MPESA_TEST_RESPONSE_400_JSON = {
    "errorMessage": MPESA_TEST_RESPONSE_TEXT
}

# result means webhook request from MPesa
MPESA_TEST_RESULTS = {
    0: 'The service request is processed successfully.',
    1032: '[STK_CB - ]Request cancelled by user'
}
MPESA_TEST_RESULT_CODE = 0
MPESA_TEST_RESPONSE_JSON_CALLBACK = {
    "MerchantRequestID": "mr_id",
    "CheckoutRequestID": "cr_id",
    "ResultCode": MPESA_TEST_RESULT_CODE,
    "ResultDesc": MPESA_TEST_RESULTS[MPESA_TEST_RESULT_CODE]
}


# =========================================
# SMS
# =========================================
SMS_USERNAME = "alexanderdidyk"
SMS_API_KEY = "57e1b11daf033d4fbbc457a619ddc8bca8b4df9b2da9cf8db4901f6c5f7eaf93"

# =========================================
# PUSH NOTIFICATIONS
# =========================================
PUSH_NOTIFICATIONS_SETTINGS = {
    "FCM_API_KEY": "AAAAS1XVRZI:APA91bG961OMbA14-DiTB4KYQX_sUnwPzjuElWiLe1LmL48dvjStSkPH3O0NPPPaB7qOwcF2-M708fbD4cs6l6_R7wAx0rbh4ZzsO_TuPs32HtKz8W7newK0pTSqF9SIdg_QohHJWxdE",
    "GCM_API_KEY": "",
    "APNS_CERTIFICATE": "/path/to/your/certificate.pem",
    "APNS_TOPIC": "com.example.push_test",
    "WNS_PACKAGE_SECURITY_ID": "[your package security id, e.g: 'ms-app://e-3-4-6234...']",
    "WNS_SECRET_KEY": "[your app secret key, e.g.: 'KDiejnLKDUWodsjmewuSZkk']",
    "WP_PRIVATE_KEY": "/path/to/your/private.pem",
    "WP_CLAIMS": {'sub': "mailto: development@example.com"}
}

# =========================================
# REQUESTS LOGGING
# =========================================
REQUEST_IGNORE_PATHS = ('admin/', 'media/')


try:
    from .local_settings import *
except ImportError:
    pass
